function dataTable = ImportProteinGeneMapping()

%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/benfulcher/Dropbox (Sydney Uni)/CurrentProjects/GWAS_DrugTargets/Code/Data/PPI_forIDmatching_final.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/11/21 17:49:23

%% Initialize variables.
filename = 'PPI_forIDmatching_final.csv';
delimiter = ',';
startRow = 2;

%% Format for each line of text:
%   column1: text (%s)
%	column2: text (%s)
%   column3: text (%s)
%	column4: text (%s)
%   column5: text (%s)
%	column6: text (%s)
%   column7: text (%s)
%	column8: text (%s)
%   column9: text (%s)
%	column10: text (%s)
%   column11: text (%s)
%	column12: text (%s)
%   column13: text (%s)
%	column14: text (%s)
%   column15: text (%s)
%	column16: text (%s)
%   column17: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
dataTable = table(dataArray{1:end-1}, 'VariableNames', {'STRINGids','HGNC_1','HGNC_2','HGNC_3','HGNC_4','HGNC_5','HGNC_6','HGNC_7','HGNC_8','HGNC_9','HGNC_10','HGNC_11','HGNC_12','HGNC_13','HGNC_14','HGNC_15','HGNC_16'});

%-------------------------------------------------------------------------------


end
