function MappedGenesidentifier = ImportIdentifierMapped(fileName)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   MAPPEDGENESIDENTIFIER = IMPORTFILE(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   MAPPEDGENESIDENTIFIER = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads
%   data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   MappedGenesidentifier = importfile('MappedGenes_identifier.csv', 2, 2626);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2017/09/06 12:16:03

if nargin < 1
    fileName = 'MappedGenes_identifier.csv';
end

%% Initialize variables.
delimiter = ',';
startRow = 2;
endRow = inf;

%% Format for each line of text:
%   column1: text (%s)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(fileName,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

% Convert to logicals:
for col = 2:8
    dataArray{col} = logical(dataArray{col});
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
MappedGenesidentifier = table(dataArray{1:end-1}, 'VariableNames', {'Name','SZP','ADHD','ASD','MDD','BIP','GWAS','LD'});

% Add logical partners (all false):
MappedGenesidentifier.Partners = false(height(MappedGenesidentifier),1);
