function pgcADeQTLWholeBloodgenes = importeMAGMAGTExfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  PGCADEQTLWHOLEBLOODGENES = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  PGCADEQTLWHOLEBLOODGENES = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  pgcADeQTLWholeBloodgenes = importfile("/Users/aurinaa/Google_drive/PostDoc/projects/GWASdrugs/data/GWASlists/GWASgenes/pgcAD_eQTLWhole_Blood_genes.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 09-Jul-2020 18:17:12

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = fixedWidthImportOptions("NumVariables", 11);

% Specify range and variable widths
opts.DataLines = dataLines;
opts.VariableWidths = [9, 5, 11, 11, 7, 8, 7, 13, 13, 13, 7];

% Specify column names and types
opts.VariableNames = ["GENE", "CHR", "START", "STOP", "NSNPS", "NPARAM", "N", "ZSTAT", "P", "PERMP", "NPERM"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
pgcADeQTLWholeBloodgenes = readtable(filename, opts);

end