function BIOMARTentrezID = importENTREZIDfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  BIOMARTENTREZID = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  BIOMARTENTREZID = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  BIOMARTentrezID = importfile("/Users/aurinaa/Google_drive/PostDoc/projects/GWASdrugs/data/GWASlists/BIOMART_entrezID.txt", [7, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 07-Jul-2020 14:29:46

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Gene", "Genename", "EntrezID"];
opts.VariableTypes = ["double", "string", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Genename", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Genename", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Gene", "TrimNonNumeric", true);
opts = setvaropts(opts, "Gene", "ThousandsSeparator", ",");

% Import the data
BIOMARTentrezID = readtable(filename, opts);

end